name: Build and Release Boolector DSO

# ←‑‑ give the default GITHUB_TOKEN write access to repository contents
permissions:
  contents: write   # needed for creating the release
  packages: read    # optional; keeps default read on packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: rockylinux:8

    steps:
      - uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          dnf -y distro-sync --refresh
          dnf -y install dnf-plugins-core
          dnf config-manager --set-enabled powertools || true
          dnf -y groupinstall "Development Tools" --nobest
          dnf -y module enable python39
          dnf -y install git cmake python39 curl ca-certificates
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Symlink python → python3
        run: ln -s /usr/bin/python3.9 /usr/bin/python || true

      - name: Download and build Boolector 3.2.2
        run: |
          git clone --branch 3.2.2 --depth 1 https://github.com/boolector/boolector
          cd boolector
          ./contrib/setup-lingeling.sh
          ./contrib/setup-btor2tools.sh
          mkdir -p build && cd build
          echo "Configuring Boolector with CMake (Python bindings disabled)..."
          cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DBTOR_ENABLE_PYTHON=OFF
          echo "Building Boolector..."
          make

      - name: Run Boolector tests
        run: |
          cd boolector/build
          ctest --output-on-failure

      - name: Set up Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . "$HOME/.cargo/env"

      - name: Test Rust bindings (boolector-rs)
        run: |
          . "$HOME/.cargo/env"
          git clone https://github.com/cdisselkoen/boolector-rs
          cd boolector-rs
          export LIBRARY_PATH="$GITHUB_WORKSPACE/boolector/build/lib:$LIBRARY_PATH"
          export LD_LIBRARY_PATH="$GITHUB_WORKSPACE/boolector/build/lib:$LD_LIBRARY_PATH"
          cargo test

      - name: Prepare artifact directory
        run: |
          mkdir -p rocky8-artifacts
          cp boolector/COPYING rocky8-artifacts/
          cp boolector/build/lib/libboolector.so rocky8-artifacts/libboolector-rocky8.so
          sha256sum rocky8-artifacts/libboolector-rocky8.so > rocky8-artifacts/libboolector-rocky8.so.sha256

      - uses: actions/upload-artifact@v4
        with:
          name: boolector-rocky8
          path: rocky8-artifacts/

  build-osx-arm64:
    name: Build for macOS ARM64
    runs-on: macos-14 # ARM64 runner

    steps:
      - uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          brew update
          for p in cmake openssl libffi python; do
            if ! brew list --versions "$p" >/dev/null 2>&1; then
              brew install "$p"
            fi
          done

      - name: Download and build Boolector 3.2.2
        run: |
          git clone --branch 3.2.2 --depth 1 https://github.com/boolector/boolector
          cd boolector
          ./contrib/setup-lingeling.sh
          ./contrib/setup-btor2tools.sh
          mkdir -p build && cd build
          echo "Configuring Boolector with CMake (Python bindings disabled)..."
          cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64 -DBTOR_ENABLE_PYTHON=OFF
          echo "Building Boolector..."
          make

      - name: Run Boolector tests
        run: |
          cd boolector/build
          ctest --output-on-failure

      - name: Set up Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Test Rust bindings (boolector‑rs)
        run: |
          . "$HOME/.cargo/env"
          git clone https://github.com/cdisselkoen/boolector-rs
          cd boolector-rs
          export LIBRARY_PATH="$GITHUB_WORKSPACE/boolector/build/lib:$LIBRARY_PATH"
          export DYLD_FALLBACK_LIBRARY_PATH="$GITHUB_WORKSPACE/boolector/build/lib:$DYLD_FALLBACK_LIBRARY_PATH"
          cargo test

      - name: Prepare artifact directory
        run: |
          mkdir -p osx-arm64-artifacts
          cp boolector/COPYING osx-arm64-artifacts/
          LIB_DYLIB=$(find boolector/build -type f \( -name 'libboolector.dylib' -o -name 'libboolector.*.dylib' \) | head -n1)
          if [ -z "$LIB_DYLIB" ]; then echo "libboolector.dylib not found"; exit 1; fi
          cp "$LIB_DYLIB" osx-arm64-artifacts/libboolector-osx-arm64.dylib
          shasum -a 256 osx-arm64-artifacts/libboolector-osx-arm64.dylib \
            > osx-arm64-artifacts/libboolector-osx-arm64.dylib.sha256

      - uses: actions/upload-artifact@v4
        with:
          name: boolector-osx-arm64
          path: osx-arm64-artifacts/

  release:
    needs: [build, build-osx-arm64]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      # checkout again so gh has a .git directory
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: boolector-rocky8
          path: boolector-rocky8

      - uses: actions/download-artifact@v4
        with:
          name: boolector-osx-arm64
          path: boolector-osx-arm64

      - name: List downloaded files
        run: |
          echo "--- Rocky Linux 8 artifacts ---"
          ls -lR boolector-rocky8
          echo "--- macOS ARM64 artifacts ---"
          ls -lR boolector-osx-arm64

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: boolector-binaries-${{ github.sha }}
        run: |
          gh release create "$TAG_NAME" \
            boolector-rocky8/libboolector-rocky8.so \
            boolector-rocky8/libboolector-rocky8.so.sha256 \
            boolector-rocky8/COPYING \
            boolector-osx-arm64/libboolector-osx-arm64.dylib \
            boolector-osx-arm64/libboolector-osx-arm64.dylib.sha256 \
            boolector-osx-arm64/COPYING \
            --title "Release $TAG_NAME" \
            --notes "Automated release of $TAG_NAME. Includes Rocky 8 (x86_64) and macOS (arm64) binaries."
